# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: test things
        run: |
          ls -l
          pwd
          whoami
          hostname
          echo $GITHUB_WORKSPACE
          ls -l "$GITHUB_WORKSPACE"
      - name: checks installation pandoc
        run: |
          which pandoc
          find / -name test-carles.md
          ls -l /
      - name: creates output
        run: |
          mkdir output
          ls -l
          sh ./build.sh
          ls -lR .
      - uses: actions/checkout@v2
      - name: sets push subdirectories
        uses: johno/actions-push-subdirectories@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: output cpina pandoc-test-output
