# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: executes one line
        run: |
          ls -l
          pwd
          whoami
          hostname
          echo $GITHUB_WORKSPACE
          ls -l "$GITHUB_WORKSPACE"
      - name: checks installation pandoc
        run: |
          which pandoc
          find / -name test-carles.md
          ls -l /
      - name: creates output
        run: |
          mkdir output
          ls -l
          bash ./build.sh
          ls -lR .
