# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container: alpine:3.8
    steps:
      - name: executes one line
        run: |
          ls -l
          pwd
          whoami
          hostname
          echo $GITHUB_WORKSPACE
      - name: test connectivity
        run: |
          ping -c 5 8.8.8.8
          ping -c 5 pina.cat
      - name: installs pandoc
        run: |
          apk add --update-cache pandoc texlive
      - name: checks installation pandoc
        run: |
          which pandoc
